# FuckPortal configuration
# max-portal-size: 单个非规则下界门的最大“内域”方块数量限制（单位：方块数）。
# 最小值为 1（仅一个洞）。若填写小于 1 的值将按 1 处理。
max-portal-size: 2048

# flood-per-tick: 每 tick 的洪水填充步数预算，防止大门生成导致主线程长时间卡顿。最小 1。
flood-per-tick: 256
# flood-per-tick: 每 tick 最多进行的“洪水扩展”步数（访问/判定的方块数）。
# 数值越小越平滑，占用主线程时间更短但完成更慢；数值越大完成更快但可能产生瞬时卡顿。
# 建议范围 64-512，默认 256。
flood-per-tick: 256
