name: fuckportal
version: '${version}'
main: byd.cxkcxkckx.fuckportal.fuckportal
api-version: 1.13
depend: []
softdepend: [ PlaceholderAPI, vault ]
authors: [ cxkcxkckx ]
commands:
  ccb:
    description: 'Confirm payment and create portal'
    usage: /ccb

permissions:
  byd.fuckportal.free:
    description: 'Exempt from portal creation fees'
    default: op
  byd.fuckportal.create:
    description: 'Exempt from portal creation fees'
    default: true