name: fuckportal
version: '${version}'
main: byd.cxkcxkckx.fuckportal.fuckportal
api-version: 1.13
depend: [  ]
softdepend: [ PlaceholderAPI ]
authors: [ cxkcxkckx ]
commands:
  example:
    description: 'The main command of ExmaplePlugin'
